// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC21YA2iDK0JmZT5Bftup7m1cFH3Rqk_JM',
    appId: '1:787865515998:web:c913346e488ad3e25b8f4f',
    messagingSenderId: '787865515998',
    projectId: 'iraqi-chemists',
    authDomain: 'iraqi-chemists.firebaseapp.com',
    storageBucket: 'iraqi-chemists.firebasestorage.app',
    measurementId: 'G-Y9D6TMX4MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwwBgNrbYVJz6CAhr-8yY26LWDg0U5wqs',
    appId: '1:787865515998:android:1ffd853878a4c9435b8f4f',
    messagingSenderId: '787865515998',
    projectId: 'iraqi-chemists',
    storageBucket: 'iraqi-chemists.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk5rqzG1hBGH59mdGP_NiTdD7bHcWt4S8',
    appId: '1:787865515998:ios:91435270fea626ed5b8f4f',
    messagingSenderId: '787865515998',
    projectId: 'iraqi-chemists',
    storageBucket: 'iraqi-chemists.firebasestorage.app',
    iosBundleId: 'com.example.iraqiChemistsSyndicateLaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk5rqzG1hBGH59mdGP_NiTdD7bHcWt4S8',
    appId: '1:787865515998:ios:91435270fea626ed5b8f4f',
    messagingSenderId: '787865515998',
    projectId: 'iraqi-chemists',
    storageBucket: 'iraqi-chemists.firebasestorage.app',
    iosBundleId: 'com.example.iraqiChemistsSyndicateLaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC21YA2iDK0JmZT5Bftup7m1cFH3Rqk_JM',
    appId: '1:787865515998:web:04616cefefa1f1045b8f4f',
    messagingSenderId: '787865515998',
    projectId: 'iraqi-chemists',
    authDomain: 'iraqi-chemists.firebaseapp.com',
    storageBucket: 'iraqi-chemists.firebasestorage.app',
    measurementId: 'G-FV3NSK436F',
  );
}
